[workspace]
members = [
  "crates/agent/common",
  "crates/codegen/*",
  "crates/core/*",
  "crates/protocols/*",
  "examples/*",
]
resolver = "3"

[workspace.package]
edition = "2024"
version = "0.1.0"

[workspace.metadata]
crane.name = "cosplay"

[workspace.dependencies]
# Core
cosplay-ancillary = { path = "./crates/core/ancillary" }
cosplay-codec = { path = "./crates/core/codec" }
cosplay-net = { path = "./crates/core/net" }
# Codegen
cosplay-generator = { path = "./crates/codegen/generator" }
cosplay-scanner = { path = "./crates/codegen/scanner" }
cosplay-xml = { path = "./crates/codegen/xml" }
# Agent
cosplay-agent = { path = "./crates/agent/common" }
cosplay-client = { path = "./crates/agent/client" }
# Protocols
cosplay-protocols-wayland = { path = "./crates/protocols/wayland" }
cosplay-protocols-xdg-shell = { path = "./crates/protocols/xdg-shell" }

anyhow = "1"
bytes = "1"
clap = "4"
futures-util = { version = "0.3", default-features = false }
heck = "0.5"
i24 = "2"
impl-tools = "0.13"
indoc = "2"
prettyplease = "0.3"
proc-macro2 = "1"
quick-xml = "0.41"
quote = "1"
rustix = "1"
sealed = "0.7"
serde = "1"
syn = "3"
thiserror = "2"
tokio = "1"
tokio-util = "0.7"
toml = { version = "1", default-features = false }

# Testing
serial_test = { version = "4", default-features = false }

# Examples
tracing = "0.1"
tracing-subscriber = "0.3"
