[workspace]
members = ["crates/*"]
resolver = "3"

[workspace.package]
edition = "2024"
version = "0.1.0"

[workspace.metadata]
crane.name = "async-wayland"

[workspace.dependencies]
async-wayland-ancillary = { path = "./crates/ancillary" }
async-wayland-xml = { path = "./crates/xml" }

bytes = "1"
futures-util = { version = "0.3", default-features = false }
i24 = "2"
impl-tools = "0.13"
quick-xml = "0.41"
rustix = "1"
sealed = "0.7"
serde = "1"
thiserror = "2"
tokio = "1"
tokio-util = "0.7"

# Testing
serial_test = { version = "4", default-features = false }
