[workspace]
members = ["crates/*"]
resolver = "3"

[workspace.package]
edition = "2024"
version = "0.1.0"

[workspace.metadata]
crane.name = "async-wayland"

[workspace.dependencies]
async-wayland-ancillary = { path = "./crates/ancillary" }
async-wayland-codec = { path = "./crates/codec" }
async-wayland-xml = { path = "./crates/xml" }

anyhow = "1"
bytes = "1"
clap = "4"
futures-util = { version = "0.3", default-features = false }
heck = "0.5"
i24 = "2"
impl-tools = "0.13"
indoc = "2"
prettyplease = "0.3"
proc-macro2 = "1"
quick-xml = "0.41"
quote = "1"
rustix = "1"
sealed = "0.7"
serde = "1"
syn = "3"
thiserror = "2"
tokio = "1"
tokio-util = "0.7"
toml = { version = "1", default-features = false }

# Testing
serial_test = { version = "4", default-features = false }
