[package]
name = "async-wayland-client"

authors.workspace = true
edition.workspace = true
exclude.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
thiserror.workspace = true

[dev-dependencies]
serial_test = { version = "3.2", default-features = false }

[lints]
workspace = true
