[package]
name = "cosplay-wayland-client"

edition.workspace = true
version.workspace = true

[dependencies]
cosplay-agent.workspace = true
cosplay-codec.workspace = true
cosplay-core-client.workspace = true
cosplay-protocols-wayland.workspace = true

sealed.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["sync"] }
tracing.workspace = true

[dev-dependencies]
cosplay-core-client = { workspace = true, features = ["test-driver"] }
