[package]
name = "async-wayland-codec"

edition.workspace = true
version.workspace = true

[dependencies]
async-wayland-ancillary.workspace = true

bytes.workspace = true
futures-util = { workspace = true, features = ["sink"] }
i24.workspace = true
impl-tools.workspace = true
sealed.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-util = { workspace = true, features = ["codec"] }
