[package]
name = "cosplay-net"

edition.workspace = true
version.workspace = true

[dependencies]
cosplay-ancillary.workspace = true

rustix = { workspace = true, features = ["net"] }
thiserror.workspace = true
tokio = { workspace = true, features = ["net"] }

[dev-dependencies]
tokio = { workspace = true, features = ["io-util", "macros", "rt-multi-thread"] }
