[package]
name = "cosplay-core-client"

edition.workspace = true
version.workspace = true

[features]
test-driver = []

[dependencies]
cosplay-agent.workspace = true
cosplay-codec.workspace = true
cosplay-net.workspace = true

cosplay-protocols-wayland.workspace = true

impl-tools.workspace = true
pin-project.workspace = true
sealed.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["macros", "sync"] }
tracing.workspace = true

[dev-dependencies]
serial_test.workspace = true
