[package]
name = "async-wayland-common"

authors.workspace = true
edition.workspace = true
exclude.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
bytes.workspace = true
futures-util = { workspace = true, features = ["sink"] }
impl-tools.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-util = { workspace = true, features = ["codec"] }

# TEMP: arguably prototyping dependencies
paste.workspace = true
sealed.workspace = true
