[package]
name = "animated"

edition.workspace = true
version.workspace = true

[dependencies]
cosplay-agent.workspace = true
cosplay-core-client.workspace = true
cosplay-protocols-wayland.workspace = true
cosplay-wayland-client.workspace = true
cosplay-xdg-shell-client.workspace = true

tokio = { workspace = true, features = ["macros", "rt-multi-thread", "time"] }
tracing.workspace = true
tracing-subscriber.workspace = true

palette = { version = "0.7", default-features = false, features = ["approx", "std"] }
